In [14]:
import numpy as np
import requests
import urllib3
from sklearn.datasets import load_svmlight_file
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, roc_curve, auc

In [7]:
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

url = "https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a9a"
response = requests.get(url, verify=False) # Verify set to false (not very safe but works)

with open("a9a", "wb") as f:
    f.write(response.content)

url = "https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a9a.t"
response = requests.get(url, verify=False) # Verify set to false (not very safe but works)

with open("a9a.t", "wb") as f:
    f.write(response.content)


In [8]:
X_train, y_train = load_svmlight_file("a9a")
X_test, y_test = load_svmlight_file("a9a.t", n_features=X_train.shape[1])

In [9]:
print(type(X_train))
print(X_train.shape)
print(type(y_train))
print(y_train.shape)
print(type(X_test))
print(X_test.shape)
print(type(y_test))
print(y_test.shape)



<class 'scipy.sparse._csr.csr_matrix'>
(32561, 123)
<class 'numpy.ndarray'>
(32561,)
<class 'scipy.sparse._csr.csr_matrix'>
(16281, 123)
<class 'numpy.ndarray'>
(16281,)


In [10]:
print(X_train.toarray())
print(y_train)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[-1. -1. -1. ... -1. -1.  1.]


In [16]:
model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

Accuracy: 84.95%


In [17]:
# evaluate the model
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[11537   898]
 [ 1552  2294]]

Classification Report:
               precision    recall  f1-score   support

        -1.0       0.88      0.93      0.90     12435
         1.0       0.72      0.60      0.65      3846

    accuracy                           0.85     16281
   macro avg       0.80      0.76      0.78     16281
weighted avg       0.84      0.85      0.84     16281

