In [2]:
import numpy as np
import requests
import urllib3
from sklearn.datasets import load_svmlight_file

In [3]:
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

url = "https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a9a"
response = requests.get(url, verify=False) # Verify set to false (not very safe but works)

with open("a9a", "wb") as f:
    f.write(response.content)

url = "https://www.csie.ntu.edu.tw/~cjlin/libsvmtools/datasets/binary/a9a.t"
response = requests.get(url, verify=False) # Verify set to false (not very safe but works)

with open("a9a.t", "wb") as f:
    f.write(response.content)


In [4]:
X_train, y_train = load_svmlight_file("a9a")
X_test, y_test = load_svmlight_file("a9a.t", n_features=X_train.shape[1])

In [5]:
print(type(X_train))
print(X_train.shape)
print(type(y_train))
print(y_train.shape)
print(type(X_test))
print(X_test.shape)
print(type(y_test))
print(y_test.shape)

<class 'scipy.sparse._csr.csr_matrix'>
(32561, 123)
<class 'numpy.ndarray'>
(32561,)
<class 'scipy.sparse._csr.csr_matrix'>
(16281, 123)
<class 'numpy.ndarray'>
(16281,)


In [6]:
print(X_train.toarray())
print(y_train)

[[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[-1. -1. -1. ... -1. -1.  1.]


In [ ]:
model = LogisticRegression()